# Generated by Django 5.2.7 on 2026-05-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_prep_access',
            field=models.BooleanField(default=False),
        ),
    ]
