# Generated by Django 5.2.1 on 2026-04-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='frameworks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='soft_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='tools',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='years_exp',
            field=models.IntegerField(default=0),
        ),
    ]
