# Generated by Django 5.2.1 on 2026-05-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_education_resume_frameworks_resume_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('skills', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('job_titles', models.JSONField(default=list)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resume.resume')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
