# Generated by Django 5.2.7 on 2026-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('color', models.CharField(default='#2563EB', max_length=20)),
                ('level', models.CharField(default='Beginner', max_length=50)),
                ('duration', models.CharField(default='4 hrs', max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
