# Generated by Django 5.2.3 on 2026-05-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_customcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcourse',
            name='modules',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customcourse',
            name='youtube_playlist',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
