# Generated by Django 5.2.3 on 2026-05-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_modules_to_custom_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcourse',
            name='resource_links',
            field=models.JSONField(default=list),
        ),
    ]
